### PR TITLE
Integrated the link page for the logged in user

### LINKED ISSUE #79: Integrating the link page for the logged in user.
A user who is already logged in should be able to make access the custom link page where he can add a custom alias for the URL. the page is already built we just need to integrate it with the current application. 

This will help the user to access the various feature after logging in only.

### PR DESCRIPTION
**Pull request by aadityasinha-dotcom**
- Linked pages for the logged-in user.
- Also added changes to the myLinks and dashboard page to link each other
- Resolves #79

### CODE REVIEW

**Comment by BRAVO68WEB** [comment]
Wait for #62 and so links created by that particular

**Comment by aadityasinha-dotcom** [comment]
> Wait for #62 and so links created by that particular

Ok

**Comment by BRAVO68WEB** [comment]
@aadityasinha-dotcom Go ahead

**Comment by BRAVO68WEB** [comment]
Fetch JWT from local storage

**Comment by aadityasinha-dotcom** [comment]
Okay

**Pull request closed without merging**
