### PR TITLE
added footer

### PR DESCRIPTION
**Pull request by akankshat05**
For #123 
Added footer to home and contributors pages.

### CODE REVIEW

**Comment by akankshat05** [comment]
> @akankshat05 Not working

Can I know what should be fixed?

**Comment by BRAVO68WEB** [comment]
@Palak-137

**Comment by Palak-137** [comment]
> > @akankshat05 Not working
> 
> Can I know what should be fixed?

1. change the font family of the footer
2. fix the position of the footer like an header 
3. footer should be visible on all the pages like: login, signup

**Comment by BRAVO68WEB** [comment]
@akankshat05

**Review by BRAVO68WEB — APPROVED** [review]
Well Done !!

**Comment by akankshat05** [comment]
@BRAVO68WEB do include it under gssoc!

**Comment by BRAVO68WEB** [comment]
@akankshat05 Done

**Pull request merged**
