### PR TITLE
made contributors page based on design

### PR DESCRIPTION
**Pull request by rakeshhotker**
created the contributors page, with hardcoded contributor details, using function template, which can be extended using the github api to fetch data and display contributor details dynamically

### CODE REVIEW

**Comment by BRAVO68WEB** [comment]
Everything is perfect just verify from Demo given like spaces below username.

@rakeshhotker Can you make it dynamic ?

Like Make it as a template and so that later on just pass name, imageurl and username and it results an card.

**Comment by rakeshhotker** [comment]
Ok, I'll work on it

**Review by Palak-137 — COMMENTED** [review]
you can put the data into the array and then map that into the cards instead of repeating the code.
also, try to make it responsive too.

**Comment by BRAVO68WEB** [comment]
> you can put the data into the array and then map that into the cards instead of repeating the code. also, try to make it responsive too.

exactly

**Comment by rakeshhotker** [comment]
Sure, thanks for the feedback

**Comment by rakeshhotker** [comment]
@Palak-137 i put the dummy data into an array using useState hook, and used array.map to pass data to the divs and also worked on making it responsive as discussed earlier

**Comment by BRAVO68WEB** [comment]
@Palak-137

**Review by Palak-137 — APPROVED** [review]

**Pull request merged**
