### PR TITLE
fix: update CORS to use site's origin on production

### LINKED ISSUE #137: URL is not minified
**Describe the bug**
URL is not minified when minify button is clicked.

**To Reproduce**
1. Go to [URL MiniFy](https://minfy.xyz/)
2. Input **https://dev.to/**
3. Click on minify button
4. Nothing is generated

**Expected behavior**
1. There should be a result, at least the shortened URL instead of nothing.

**Screenshots**
Screenshot (356)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: **Brave**
 - Version: ---

**Additional context**
On checking the error message, I realized it was a CORS problem.

**Possible Solution**
Include https://minfy.xyz/ as part of the allowed origins. It's currently localhost

**I will be happy to work on this**

### PR DESCRIPTION
**Pull request by Olaleye-Blessing**
Resolve #137

### CODE REVIEW

**Comment by BRAVO68WEB** [comment]
@Olaleye-Blessing still not working

**Comment by Olaleye-Blessing** [comment]
It's not working because you're looking at the preview mode, not the production mode. The origin is going to change because vercel gives a new URL for each branch(this pull request branch in this case, check the circled part of the screenshot). And I think the NODE_ENV for previews is always `development` because the `Access-Control-Allow-Origin` header still has a value `http://localhost:3000`.

Screenshot (364)_LI

We can test this by setting the origin to `https://url-minify-git-fork-olaleye-blessing-fixurlminified-bravo68web.vercel.app`(I hope it stays the same after making another push).

**Comment by Olaleye-Blessing** [comment]
@BRAVO68WEB

**Comment by BRAVO68WEB** [comment]
Right @Olaleye-Blessing 

I am not into Frontend that much
I am a bit dumb 😂😂😂

**Comment by BRAVO68WEB** [comment]
My bad

**Comment by BRAVO68WEB** [comment]
It's working now

**Comment by Olaleye-Blessing** [comment]
After doing this `NODE_ENV=production`, right?

**Comment by Olaleye-Blessing** [comment]
> https://github.com/BRAVO68WEB/url-minify/blob/1b5389e06c09eff2fdf19c9e2e4a9d9fdf426496/backend/index.js#L18

That line needs to be updated to `line 17` to make things work locally. Should I create a pull request for it?

**Comment by BRAVO68WEB** [comment]
Naah It's Ok

Vercel link always changes

**Comment by BRAVO68WEB** [comment]
Well done man, thanks for making 2 PRs in 24 Hrs as an external contributor

**Comment by BRAVO68WEB** [comment]
@Olaleye-Blessing Well done man, thanks for making 2 PRs in 24 Hrs as an external contributor

**Pull request merged**
