### PR TITLE
Responsive pages

### LINKED ISSUE #81: Make all pages responsive.
**Describe the bug**
The pages doesn't scale well for mobile devices.

Screenshot

I would like to work on this issue under GSSOC 2022.

### PR DESCRIPTION
**Pull request by Tejas-117**
- Made all pages responsive to all devices.
- Removed inline styling and moved it to seperate files (reduced redundant code).

 fixes #81

### CODE REVIEW

**Comment by BRAVO68WEB** [comment]
The Entire site broke down 

@Palak-137 See to this.

**Comment by Tejas-117** [comment]
@BRAVO68WEB I reproduced the issue locally, and it seem to break only in production. But works completely in development mode. The issue seems to be regarding serving css files.

**Comment by Tejas-117** [comment]
@BRAVO68WEB It works fine in production mode now.

**Review by Palak-137 — COMMENTED** [review]
@Tejas-117  can you please also make the dashboard responsive?

**Comment by Tejas-117** [comment]
@Palak-137 I didn't see dashboard page.

**Comment by Palak-137** [comment]
navigate to /dashboard from homepage

**Comment by Tejas-117** [comment]
@Palak-137 Got it, working on it.

**Comment by Tejas-117** [comment]
@Palak-137  Can you review it ?? 
Let me know what should be changed.

**Review by Palak-137 — APPROVED** [review]

**Comment by BRAVO68WEB** [comment]
@allcontributors please add @Tejas-117 for code

**Pull request merged**
