### PR TITLE
feat : added QR code

### PR DESCRIPTION
**Pull request by Lunatix01**
added QR code to the frontend now it works fine

### CODE REVIEW

**Comment by Lunatix01** [comment]
sorry by a mistake i deleted the .env.example

**Comment by BRAVO68WEB** [comment]
Can you fix merge conflicts and PR again

**Comment by Lunatix01** [comment]
Merge conflicts fixed ✅

**Comment by Lunatix01** [comment]
> Can you fix merge conflicts and PR again

can you check why vercel is not deploying please?

**Comment by BRAVO68WEB** [comment]
Delete your package-lock.json and PR again

Error 
```
SyntaxError: /vercel/path0/frontend/package-lock.json: Unexpected token : in JSON at position 73065
--
01:50:10.709 | at JSON.parse (<anonymous>)
01:50:10.709 | at Object._readFile (/vercel/f51cfbb0fe1c2174/.build-utils/node_modules/@vercel/build-utils/dist/index.js:24856:16)
01:50:10.709 | at async Promise.all (index 0)
01:50:10.709 | at async scanParentDirs (/vercel/f51cfbb0fe1c2174/.build-utils/node_modules/@vercel/build-utils/dist/index.js:34695:52)
01:50:10.710 | at async getNodeVersion (/vercel/f51cfbb0fe1c2174/.build-utils/node_modules/@vercel/build-utils/dist/index.js:34663:29)
01:50:10.710 | at async Object.build (/vercel/f51cfbb0fe1c2174/.build-utils/.builder/node_modules/@vercelruntimes/next/dist/index.js:31:197791)
01:50:10.710 | at async Ttt (/var/task/sandbox.js:196:7838)

```

**Comment by Lunatix01** [comment]
> Delete your package-lock.json and PR again
> 
> Error
> 
> ```
> SyntaxError: /vercel/path0/frontend/package-lock.json: Unexpected token : in JSON at position 73065
> --
> 01:50:10.709 | at JSON.parse (<anonymous>)
> 01:50:10.709 | at Object._readFile (/vercel/f51cfbb0fe1c2174/.build-utils/node_modules/@vercel/build-utils/dist/index.js:24856:16)
> 01:50:10.709 | at async Promise.all (index 0)
> 01:50:10.709 | at async scanParentDirs (/vercel/f51cfbb0fe1c2174/.build-utils/node_modules/@vercel/build-utils/dist/index.js:34695:52)
> 01:50:10.710 | at async getNodeVersion (/vercel/f51cfbb0fe1c2174/.build-utils/node_modules/@vercel/build-utils/dist/index.js:34663:29)
> 01:50:10.710 | at async Object.build (/vercel/f51cfbb0fe1c2174/.build-utils/.builder/node_modules/@vercelruntimes/next/dist/index.js:31:197791)
> 01:50:10.710 | at async Ttt (/var/task/sandbox.js:196:7838)
> ```
deleted package-lock.json but the problem is still remaining

**Review by BRAVO68WEB — COMMENTED** [review]
Ok

**Pull request merged**
