### PR TITLE
Added start over button(#118)

### PR DESCRIPTION
**Pull request by 404-Terror**
- Added start over button to refresh the input box
- Changed transition duration of QR code from 1 to 0.7

### CODE REVIEW

**Review by Palak-137 — COMMENTED** [review]
good work, but can also work on the minify button CSS,
as you see on entering URL it turns out to be grey and opaque. 
w could do something else instead of that.

**Comment by BRAVO68WEB** [comment]
> good work, but can also work on the minify button CSS, as you see on entering URL it turns out to be grey and opaque. w could do something else instead of that.

Agreed and also take my point.

Right @Palak-137

**Comment by 404-Terror** [comment]
> @404-Terror While start over button is visible, minify button should be be disable

Okay I will do the same.

**Comment by 404-Terror** [comment]
> good work, but can also work on the minify button CSS, as you see on entering URL it turns out to be grey and opaque. w could do something else instead of that.

Like changing the CSS of disabled button??

**Pull request closed without merging**
