### PR TITLE
Integrate login and signup feature

### PR DESCRIPTION
**Pull request by Tejas-117**
- integrate frontend and backend for login and signup feature
- add custom validations and messages to update users on their current status

### CODE REVIEW

**Comment by BRAVO68WEB** [comment]
What the issue now?  Like what needs to be done with it.

**Comment by Tejas-117** [comment]
@BRAVO68WEB Check pages/_app.js in frontend directory. We need to add user to context as soon as they are authenticated.

**Comment by BRAVO68WEB** [comment]
Ok Go it

**Comment by BRAVO68WEB** [comment]
Fixed #62

**Pull request closed without merging**
