### PR TITLE
feat: integrate github api to fetch contributors

### LINKED ISSUE #124: integrate the github api
To show the contributors you can implement the GitHub API to reduce the manual work.
refer to issue: #122

### PR DESCRIPTION
**Pull request by Olaleye-Blessing**
Resolve #124 

Screenshot (359)

Screenshot (360)

Screenshot (361)

Screenshot (362)

Screenshot (363)

### CODE REVIEW

**Review by BRAVO68WEB — CHANGES_REQUESTED** [review]
Can you link credits button in navigation to open this page?

**Comment by BRAVO68WEB** [comment]
Rest is fine.

Are you contributing for GSSoC ?

**Comment by Olaleye-Blessing** [comment]
> Can you link credits button in navigation to open this page?

It's linked.

**Comment by Olaleye-Blessing** [comment]
> Rest is fine.
> 
> Are you contributing for GSSoC ?

No

**Comment by BRAVO68WEB** [comment]
> > Can you link credits button in navigation to open this page?
> 
> It's linked. Or what do you mean by linked? Clicking on `CREDITS` on navigation loads the contribution page.

Its not working on mobile view. PC is working

**Comment by BRAVO68WEB** [comment]
> > Rest is fine.
> > Are you contributing for GSSoC ?
> 
> No

Great

**Comment by Olaleye-Blessing** [comment]
> > > Can you link credits button in navigation to open this page?
> > 
> > 
> > It's linked. Or what do you mean by linked? Clicking on `CREDITS` on navigation loads the contribution page.
> 
> Its not working on mobile view. PC is working

Oh! My bad. I didn't check that. I've fixed it.

I have a question though. Is there a reason for having different boxes for mobiles and Desktops?

**Comment by BRAVO68WEB** [comment]
> > > > Can you link credits button in navigation to open this page?
> > > 
> > > 
> > > It's linked. Or what do you mean by linked? Clicking on `CREDITS` on navigation loads the contribution page.
> > 
> > 
> > Its not working on mobile view. PC is working
> 
> Oh! My bad. I didn't check that. I've fixed it.
> 
> I have a question though. Is there a reason for having different boxes for mobiles and Desktops?

At 

> > > > Can you link credits button in navigation to open this page?
> > > 
> > > 
> > > It's linked. Or what do you mean by linked? Clicking on `CREDITS` on navigation loads the contribution page.
> > 
> > 
> > Its not working on mobile view. PC is working
> 
> Oh! My bad. I didn't check that. I've fixed it.
> 
> I have a question though. Is there a reason for having different boxes for mobiles and Desktops?

Naah not at the timing

**Review by BRAVO68WEB — APPROVED** [review]

**Pull request merged**
